//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WUG.Client.Shared.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WUG.Client.Shared.Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;EventID&quot;:952,&quot;Name&quot;:&quot;.Net TechTalks&quot;,&quot;TakePlaceFrom&quot;:&quot;2017-08-01T17:00:00&quot;,&quot;TakePlaceTo&quot;:&quot;2017-08-01T20:30:00&quot;,&quot;EventType&quot;:0,&quot;Branch&quot;:{&quot;BranchID&quot;:2,&quot;Name&quot;:&quot;Brno&quot;,&quot;IsActive&quot;:true,&quot;Country&quot;:{&quot;CountryID&quot;:1,&quot;Name&quot;:&quot;Česká republika&quot;,&quot;CountryCode&quot;:&quot;cz&quot;,&quot;CultureCode&quot;:&quot;cs-CZ&quot;}},&quot;EventPlace&quot;:{&quot;EventPlaceID&quot;:44,&quot;BranchID&quot;:2,&quot;Name&quot;:&quot;Fakulta informatiky Masarykovy univerzity&quot;},&quot;Speakers&quot;:[{&quot;SpeakerID&quot;:233,&quot;FirstName&quot;:&quot;Jan&quot;,&quot;LastName&quot;:&quot;Vorlicek&quot;,&quot;Company&quot;:&quot;Microsoft&quot;,&quot;Title&quot;:null,&quot;Suffix&quot;:null,&quot;DisplayedTitles&quot;:null, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetUpcomingEvents {
            get {
                return ResourceManager.GetString("GetUpcomingEvents", resourceCulture);
            }
        }
    }
}
