#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WUG.Client.Droid.Resource", IsApplication=true)]

namespace WUG.Client.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_calendar_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int EventInfoBranch = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int EventInfoDate = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int EventInfoDateContainer = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int EventInfoTextLayout = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int EventInfoTitle = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EventInfoListViewItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int BaseAppTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int BaseRobotoStyle = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int BlueLargeLightStyle = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int BlueMediumLightStyle = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int BlueMediumNormalStyle = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int BoldCondensedStyle = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int BoldStyle = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int CondensedStyle = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int GreyLightStyle = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int GreyMediumLightStyle = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int GreyNormalStyle = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int LargeLightStyle = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int LargeNormalStyle = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int LightStyle = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int MediumBoldStyle = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int MediumCondensedStyle = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int MediumLightStyle = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int MediumNormalStyle = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int NormalStyle = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
